services:
  chatty-chat:
  ports:
    - 3001:3001
  build:
    context: .
  depends_on:
    chatty-chat-db:
      condition: service_healthy

  chatty-chat-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: chatty_chat
    ports:
      - 27017:27017
    volumes:
      - chatty-chat-db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]

volumes:
  chatty-chat-db:
